version: "3.9"
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpass
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_DATABASE: mydb
      KC_DB_PASSWORD: mypass
      KC_DB_USERNAME: myuser
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
